### ISSUE TITLE
is  "background: red;" valid in the example?

### ISSUE THREAD

**Issue by imranansari** [Pixate/RubyMotion-PixateFreestyle#1]
The snippet below from the example doesnt work

 button {
        background: red;
    }

but this works

```
background-color: red;
```

**Comment by pcolton** [comment]
That seems like an old sample. Background is no longer supported. See
http://www.pixate.com/documentation.html for the latest property docs.
Sorry about that, we'll fix it.
-Paul

On Feb 1, 2013, at 1:48 PM, Imran Ansari notifications@github.com wrote:

The snippet below from the example doesnt work

button {
background: red;
}

but this works

background-color: red;

 —
Reply to this email directly or view it on
GitHubhttps://github.com/Pixate/RubyMotion-Pixate/issues/1.

**Comment by andrewhavens** [comment]
FYI for anyone who comes across this page, the documentation has been moved to http://www.freestyle.org
