### ISSUE TITLE
More confidence about layouts

### ISSUE THREAD

**Issue by ajbraus** [Pixate/RubyMotion-PixateFreestyle#6]
I'm really excited to use Pixate, but I don't know about layouts. Can PIxate position elements on the screen as well, such as position:relative, position:absolute, top:10px, left:10px? Or do I have to rely on Objective C methods for this basic styling and can only change colors/fonts with Pixate?

Thanks!

**Comment by bobspace** [comment]
Yes, you can position elements via CSS. Use the top and left properties. More information [here](http://cdn.pixate.com/docs/engine/ios/2.0RC1/Pixate%20Engine%20for%20iOS%20Styling%20Reference.html)
